name: urban_x_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  rename: ^3.1.0
  google_fonts: 5.0.0
  flutter_svg: 2.0.0
  go_router: ^16.3.0
  cached_network_image: ^3.4.1
  firebase_auth: ^5.1.1
  firebase_core: ^3.2.0
  image_picker: ^1.2.0
  http: ^1.5.0
  onnxruntime: ^1.4.1
  image: ^4.5.4
  path_provider: ^2.1.5
  cloud_functions: ^5.6.2
  flutter_dotenv: ^6.0.0
  provider: ^6.1.5+1
  json_serializable: ^6.11.1
  json_annotation: ^4.9.0
  cloud_firestore: ^5.6.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/mock/
    - assets/models/
    - .env
